apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- rbac.yaml
- daemonset.yaml

secretGenerator:
- name: fluentd-secret
  files:
  - google-application-credentials.json

generatorOptions:
  disableNameSuffixHash: true
