apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- daemonset.yaml
- configmap.yaml

secretGenerator:
- name: google-fluentd-secret
  namespace: kube-system
  files:
  - google-application-credentials.json

generatorOptions:
  disableNameSuffixHash: true
